version: '3.3'
services:
  mysql:
      image: mysql:8.0.26
      container_name: webdev-mysql
      volumes: 
        - ./confs/mysql_db:/var/lib/mysql
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test_db
        MYSQL_USER: devuser
        MYSQL_PASSWORD: devpass
      ports:
        - "3307:3306"
  mariadb:
    image: mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: admin
    restart: unless-stopped
    volumes:
     - mariadb_data:/var/lib/mysql
  postgres:
    image: 'postgres'
    container_name: postgres
    restart: always
    environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        PGDATA: /var/lib/postgresql/data
    ports:
    - '5432:5432'
    volumes:
    - postgres_data:/var/lib/postgresql/data
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db
  redis:
    image: redis
    container_name: redis
    command: /bin/sh -c "redis-server --requirepass $$REDIS_HOST_PASSWORD"
    env_file:
      - redis.env #you must write REDIS_HOST_PASSWORD=admin on file redis.env
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: always
  postgres:
    image: 'postgres'
    container_name: postgres
    restart: always
    environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        PGDATA: /var/lib/postgresql/data
    ports:
    - '5432:5432'
    volumes:
    - ./database:/var/lib/postgresql/data
  mssql:
    container_name: mssql-db
    hostname: mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Passw0rd'
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: 'Developer' 
      MSSQL_TCP_PORT: 1433 
    ports: 
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'ekanoon'
      MYSQL_ROOT_PASSWORD: '97N7R5!&f1At'
      TZ: Asia/Tehran
      # command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-time-zone=+03:30']
    ports:
      - "6033:3306"
    volumes:
      - ./data/conf.d:/etc/mysql/conf.d
      - ./data/logs:/logs
      - /usr/local/var/mysql:/var/lib/mysqldocker container stop
volumes:
  mysql_data:
  redis_data:
  mongodb_data:
  postgres_data:
  mariadb_data:
